# Generated by Django 6.0.7 on 2026-07-30 17:54

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntitySchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("fields_definition", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entity Schema",
                "verbose_name_plural": "Entity Schemas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EntityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="django_baas.entityschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Record",
                "verbose_name_plural": "Entity Records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["schema", "is_deleted", "-created_at"],
                        name="django_baas_schema__222085_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["data"], name="entity_record_data_gin"
                    ),
                ],
            },
        ),
    ]
